// Publication approved on 2026-09-23. Keep real publication dates when revising.
// Prices are populated from checkout configuration by the renderer, never copied.
export const blogSources = {
    appleReport: { title: 'Apple: configurar Tiempo en pantalla', url: 'https://support.apple.com/es-mx/guide/iphone/iphbfa595995/ios', accessed: '2026-09-23' },
    appleLimits: { title: 'Apple: horarios y límites de Tiempo en pantalla (iOS 27)', url: 'https://support.apple.com/es-lamr/guide/iphone/-iphb0c7313c9/ios', accessed: '2026-09-23' },
    who: { title: 'OMS Europa: Teens, screens and mental health (2024; datos de 2018 y 2022)', url: 'https://www.who.int/europe/news/item/25-09-2024-teens--screens-and-mental-health', accessed: '2026-09-23' },
    apa: { title: 'APA: Health advisory on social media use in adolescence', url: 'https://www.apa.org/topics/social-media-internet/health-advisory-adolescent-social-media-use', accessed: '2026-09-23' },
    brickProduct: { title: 'Brick: producto y precio anunciado', url: 'https://getbrick.com/products/grey-brick', accessed: '2026-09-23' },
    brickFAQ: { title: 'Brick: compatibilidad y preguntas frecuentes', url: 'https://getbrick.com/pages/faq', accessed: '2026-09-23' },
    brickTerms: { title: 'Brick: términos, sección 6 (modelo de pago)', url: 'https://getbrick.com/pages/terms-of-service', accessed: '2026-09-23' },
    focoSupport: { title: 'Foco: funcionamiento, compatibilidad y ayuda', url: 'https://getfoco.co/soporte/', accessed: '2026-09-23' },
    focoPrice: { title: 'Foco: precio y opciones de compra', url: 'https://getfoco.co/comprar/', accessed: '2026-09-23' },
    focoTerms: { title: 'Foco: condiciones de compra, envíos y devoluciones', url: 'https://getfoco.co/compra/', accessed: '2026-09-23' },
};

export const blogArticles = [
    {
        slug: 'como-usar-menos-el-celular', status: 'published', publishedAt: '2026-09-23', preparedAt: '2026-09-23', category: 'Hábitos', number: '01',
        title: 'Cómo usar menos el celular: un plan de 7 días',
        description: 'Un plan práctico para identificar el scroll automático, proteger un momento del día y medir el cambio sin borrar todas tus apps ni prometer una cura.',
        dek: 'No tienes que desaparecer de internet. Empieza por recuperar un momento que sí quieres vivir.',
        cover: 'desk', sources: ['appleReport', 'focoSupport'], related: ['adiccion-redes-sociales', 'foco-vs-tiempo-en-pantalla', 'cuanto-cuesta-foco'],
        answer: 'Para usar menos el celular, identifica qué app abres sin querer, elige un momento concreto para dejarla en pausa y prepara algo que hacer en su lugar. Revisa el resultado al final de una semana. Este plan es un experimento de hábitos, no un tratamiento ni una promesa de cambio en siete días.',
        sections: [
            { id: 'empieza-por-un-momento', title: 'Menos pantalla no siempre significa mejor uso', html: `<p>Una videollamada con alguien que extrañas y veinte minutos de scroll que no querías hacer aparecen en la misma pantalla. No necesitan la misma solución. Antes de proponerte una cifra, termina esta frase: <strong>“Quiero que el celular deje de interrumpir…”</strong>.</p><p>Puede ser el desayuno, el inicio del trabajo o ese rato antes de dormir. Elige uno. “Nunca más perder tiempo” no te dice qué hacer a las siete de la noche. “Cenar sin abrir Instagram” sí.</p><p>En el iPhone, Tiempo en pantalla muestra actividad por apps, notificaciones y consultas del dispositivo. Úsalo para observar tu situación, no para compararte con otra persona. <a href="#fuente-appleReport">Consulta la guía de Apple</a>.</p>` },
            { id: 'plan-de-siete-dias', title: 'Siete días, una decisión pequeña cada día', html: `<ol class="day-plan"><li><strong>Día 1 · Mira sin corregir.</strong><p>Anota la app que más interrumpe el momento elegido. Registra cuándo la abriste y qué estabas haciendo justo antes. No hace falta vigilar cada minuto del día.</p></li><li><strong>Día 2 · Define lo que sí quieres hacer.</strong><p>Escribe una acción concreta: leer unas páginas, terminar una tarea, caminar o conversar. Deja preparado lo necesario. Si cierras una app pero no sabes qué sigue, la alternativa continúa siendo el teléfono.</p></li><li><strong>Día 3 · Reduce las invitaciones.</strong><p>Revisa las notificaciones de esa app y conserva las que realmente necesitas. Aparta el acceso del lugar donde lo tocas por costumbre. No silencies avisos importantes de salud, trabajo o personas a tu cargo.</p></li><li><strong>Día 4 · Prueba un límite.</strong><p>Empieza por los controles que ya tiene tu teléfono. Si los saltas casi sin pensar, prueba una barrera distinta: dejar el equipo en otra habitación o pausar las apps elegidas con una herramienta como Foco.</p></li><li><strong>Día 5 · Diseña la excepción.</strong><p>Decide cómo seguirán disponibles llamadas, mapas, autenticadores y comunicación esencial. Haz una prueba breve antes de depender del bloqueo durante una jornada completa.</p></li><li><strong>Día 6 · Repite en el mismo momento.</strong><p>No amplíes el plan por entusiasmo. Repite el contexto que elegiste y anota qué lo hizo fácil o difícil. Un día atípico sirve para ajustar el plan, no para declararlo un fracaso.</p></li><li><strong>Día 7 · Revisa y elige.</strong><p>Compara ese momento con el comienzo: ¿interrumpiste menos lo que querías hacer? Conserva una medida útil, cambia una que estorbó y decide si quieres probar otra semana.</p></li></ol>` },
            { id: 'ejemplo-con-foco', title: 'Un ejemplo: un modo para leer', html: `<p>En Foco puedes crear un modo “Lectura” y seleccionar las apps y sitios que quieres pausar, o permitir solo los que necesitas. No bloquees una categoría entera por inercia si también contiene una herramienta importante.</p><p>Elige una duración o <strong>Hasta volver</strong>. En una sesión con duración, el bloqueo termina al cumplirse el tiempo; para terminar antes, o cerrar una sesión Hasta volver, usas la tarjeta vinculada. Dejarla en un sitio deliberado añade un paso físico entre el impulso y volver a la app.</p><p>Foco ofrece tres desbloqueos de emergencia por cuenta; no se renuevan automáticamente. Conoce esa salida antes de comenzar. La tarjeta no hace la decisión por ti: sirve para sostener una decisión que ya tomaste. <a href="#fuente-focoSupport">Ver cómo funciona y sus límites</a>.</p><!-- visual:modos -->` },
            { id: 'como-medir', title: 'Mide lo que querías recuperar', html: `<p>Guarda una nota con tres columnas: momento, interrupción y qué hiciste en su lugar. “Leí después de cenar sin abrir el feed” puede ser más útil que una reducción del tiempo total en un día en el que también necesitabas trabajar desde el celular.</p><p><strong>Mi tiempo, dentro de Foco, registra sesiones de Foco; no equivale a minutos que habrías pasado en redes.</strong> Para observar el uso de las apps, consulta también el reporte del sistema. No restes ambas cifras para inventar “horas recuperadas”.</p><p>Si un límite no funciona, reduce el alcance: una app, un lugar, un momento. Si el uso te produce malestar importante, perjudica de forma persistente tu sueño, tus relaciones o tus responsabilidades, no lo conviertas en una prueba de voluntad: busca apoyo profesional. <a href="/blog/adiccion-redes-sociales/">Aquí explicamos cómo distinguir un hábito de un problema que merece ayuda</a>.</p>` },
        ],
        questions: [
            ['¿Tengo que borrar las redes sociales?', 'No necesariamente. Puedes empezar por un momento o una app y conservar los usos que sí te aportan. Si decides eliminar una, prepara otra forma de mantener los contactos o actividades importantes.'],
            ['¿Cuánto debería bajar mi tiempo en pantalla?', 'Este plan no fija un objetivo universal. Compara tu propio contexto y el efecto sobre la actividad que querías proteger; una cifra aislada no describe la calidad del uso.'],
        ],
    },
    {
        slug: 'adiccion-redes-sociales', status: 'published', publishedAt: '2026-09-23', preparedAt: '2026-09-23', category: 'Bienestar digital', number: '02',
        title: 'Adicción a las redes sociales: cuándo el uso empieza a ser un problema',
        description: 'Qué observar si sientes que no puedes dejar las redes sociales, qué dicen los datos y cuándo buscar ayuda. Sin autodiagnósticos ni promesas de una app.',
        dek: 'No es solo cuánto tiempo pasas ahí. También importa lo que está quedando fuera.',
        cover: 'analytics', medical: true, sources: ['who', 'apa', 'focoSupport'], related: ['como-usar-menos-el-celular', 'foco-vs-tiempo-en-pantalla'],
        answer: 'Si te preocupa una posible adicción al celular o a las redes sociales, observa la dificultad para parar y las consecuencias en tu vida, no solo el número de horas. Un artículo o un contador no pueden diagnosticarte. Si hay malestar persistente o se afectan tus actividades y relaciones, consulta a un profesional de salud mental.',
        sections: [
            { id: 'que-observar', title: 'Ponle nombre a lo que está pasando', html: `<p>“Soy adicto al celular” puede expresar muchas cosas: abrir una app por costumbre, sentir que se te va la noche o estar pasando un momento difícil y refugiarte en el feed. No son situaciones idénticas. En esta guía usamos <strong>uso problemático</strong> para hablar de dificultades y consecuencias que conviene atender, sin asignar un diagnóstico.</p><p>La APA recomienda prestar atención, en adolescentes, a patrones que interfieren con sus actividades y rutinas. Su orientación incluye dificultad para detener el uso y dejar de lado otras actividades. Es una guía para esa población, no un test que permita diagnosticar a cualquier lector. <a href="#fuente-apa">Fuente: APA</a>.</p><p>Para preparar una conversación con un profesional, describe situaciones concretas: qué querías hacer, qué terminó pasando, con qué frecuencia y cómo te sentiste. “Me quedé mirando videos cuando quería dormir varias noches” comunica más que una etiqueta.</p>` },
            { id: 'lo-que-dicen-los-datos', title: 'Un dato importante, con sus límites', html: `<p>La OMS Europa informó que el porcentaje de adolescentes con señales de uso problemático de redes pasó de 7% en 2018 a 11% en 2022. El gráfico muestra ambas mediciones y el alcance de la encuesta. <a href="#fuente-who">Fuente: OMS / HBSC</a>.</p><!-- visual:who --><p>Estos datos <strong>no estiman la prevalencia en adultos colombianos</strong>, no predicen tu situación y no muestran que una app de bloqueo sea un tratamiento. Tampoco permiten atribuir toda dificultad de salud mental a las redes. El mismo informe reconoce que su uso puede ofrecer conexión y apoyo.</p>` },
            { id: 'una-conversacion-sin-culpa', title: 'Una conversación útil, sin culpa', html: `<p>En lugar de contar “fallos”, puedes escribir: “Me preocupa que…”, “Lo noto especialmente cuando…” y “Necesito ayuda con…”. Si acompañas a alguien, pregunta antes de proponer restricciones. Su contexto puede incluir trabajo, estudio, amistades o una fuente importante de apoyo.</p><p>Si se trata de un menor, la conversación y las herramientas deben ser apropiadas para su edad y situación. No presentes un bloqueo secreto como sustituto del acompañamiento familiar o profesional. Los controles parentales y una herramienta de autocontrol para adultos responden a necesidades diferentes.</p><p>Este artículo es información general elaborada por Foco, una marca que vende una herramienta de enfoque. <strong>No ha sido presentado como una evaluación clínica ni sustituye atención profesional.</strong></p>` },
            { id: 'que-puedes-probar', title: 'Qué puedes probar mientras observas tu uso', html: `<p>Si buscas un cambio cotidiano, empieza con un objetivo limitado: una comida sin feed o un espacio de trabajo sin una app concreta. Mantén accesibles las vías importantes de comunicación. Prepara una actividad alternativa y revisa si el cambio te resulta útil, en lugar de imponer una prohibición total.</p><p>El <a href="/blog/como-usar-menos-el-celular/">plan de siete días</a> es una propuesta de organización, no una intervención clínica validada. Puedes adaptarlo o dejarlo si no responde a lo que necesitas.</p><p>Foco permite pausar apps elegidas y usar una tarjeta física para cerrar determinadas sesiones. Puede servir como una barrera voluntaria dentro de una rutina. <strong>No diagnostica ni trata una adicción</strong>, y no tenemos un ensayo clínico que demuestre que Foco lo haga. No uses una compra como condición para pedir ayuda. <a href="#fuente-focoSupport">Alcance del producto</a>.</p>` },
            { id: 'cuando-pedir-ayuda', title: 'Cuándo buscar apoyo', html: `<p>Si la situación te genera angustia, se repite a pesar de tus intentos de cambiarla o está afectando tus responsabilidades, tu descanso o tus relaciones, habla con un profesional de salud mental o con tu servicio de salud. No necesitas esperar a que un contador llegue a cierto número.</p><p>Puedes llevar ejemplos de lo que ocurre y de los cambios que ya intentaste. Eso ayuda a explorar el contexto, en vez de asumir que el teléfono explica todo. Un bloqueador puede ser una herramienta práctica; una evaluación profesional responde a otra pregunta.</p>` },
        ],
        questions: [
            ['¿Muchas horas de pantalla significan adicción?', 'Por sí solas no permiten un diagnóstico. Importan el contexto, el control sobre el uso y sus consecuencias. Si te preocupa tu situación, busca una evaluación profesional.'],
            ['¿Foco reemplaza la terapia?', 'No. Foco es una herramienta de enfoque y no se presenta como tratamiento para adicción, ansiedad, depresión u otra condición de salud.'],
        ],
    },
    {
        slug: 'foco-vs-tiempo-en-pantalla', status: 'published', publishedAt: '2026-09-23', preparedAt: '2026-09-23', category: 'Comparaciones', number: '03',
        title: 'Foco vs. Tiempo en pantalla: qué opción te conviene',
        description: 'Compara los controles gratuitos del iPhone con la tarjeta Foco: límites, horarios, sesiones y qué mide cada opción. Incluye las novedades documentadas para iOS 27.',
        dek: 'A veces basta con lo que ya tiene tu iPhone. A veces necesitas que volver al feed implique levantarte.',
        cover: 'modos', sources: ['appleReport', 'appleLimits', 'focoSupport', 'focoPrice'], related: ['como-usar-menos-el-celular', 'foco-vs-brick-colombia', 'cuanto-cuesta-foco'],
        answer: 'Empieza por Tiempo en pantalla si quieres conocer tu uso y establecer límites sin comprar nada. Considera Foco si buscas pausar apps por modos y añadir una tarjeta física al cierre de la sesión. Pueden complementarse: el reporte de uso del iPhone y el tiempo de sesiones de Foco miden cosas distintas.',
        sections: [
            { id: 'diferencia-principal', title: 'La diferencia está en cómo vuelves', html: `<p>La pregunta útil no es cuál producto “gana”, sino qué ocurre cuando quieres saltarte tu propio plan. Si un límite del sistema te sirve, no hace falta añadir un dispositivo. Si necesitas un gesto fuera de la pantalla, la tarjeta de Foco puede encajar mejor en ese momento.</p><p>Somos Foco y vendemos una de las opciones. Esta comparación explica funciones y límites, no una prueba independiente de eficacia. No afirmamos que una alternativa reduzca más el uso que la otra.</p><!-- visual:screen-time-table -->` },
            { id: 'que-ofrece-apple', title: 'Qué ofrece Tiempo en pantalla hoy', html: `<p>La documentación actual de Apple para iOS 27 describe horarios con distintos intervalos, límites por categorías y opciones para mantener apps y contactos siempre permitidos. También permite consultar el uso. No sería correcto compararlo como si solo tuviera un contador y una única alarma. <a href="#fuente-appleLimits">Ver funciones y requisitos de versión</a>.</p><p>Para explorar esas opciones en iOS 27, entra en Configuración, abre Tiempo en pantalla y revisa Horario de Tiempo en pantalla y Límites de tiempo. Los nombres y posibilidades cambian según la versión. Si tienes otra, selecciona tu versión en la guía de Apple.</p><p>Para acompañar el uso de un menor, revisa las opciones de familia de Apple. Foco no sustituye ese sistema de gestión parental. <a href="#fuente-appleReport">Guía de configuración</a>.</p>` },
            { id: 'que-anade-foco', title: 'Qué añade la tarjeta Foco', html: `<p>En Foco agrupas tus decisiones en modos: trabajo, lectura, descanso o el nombre que tenga sentido para ti. Puedes bloquear lo seleccionado o permitir solo lo seleccionado. Las rutinas programan sesiones para los días y horarios que elijas.</p><p>Una sesión con duración termina al vencer el tiempo. Con <strong>Hasta volver</strong>, decides volver con la tarjeta. Para terminar antes de lo previsto también se usa la tarjeta; existen tres desbloqueos de emergencia por cuenta que no se recargan automáticamente.</p><p>Foco necesita un iPhone con iOS 17.6 o posterior y los permisos correspondientes. No funciona en Android. La tarjeta se paga una vez, sin suscripción. Consulta la compatibilidad antes de comprar. <a href="#fuente-focoSupport">Funcionamiento de Foco</a>.</p><!-- visual:rutinas -->` },
            { id: 'elige-segun-tu-caso', title: 'Elige según el problema, no según la lista más larga', html: `<h3>Quiero saber dónde se va mi tiempo</h3><p>Empieza por el reporte de uso de Tiempo en pantalla. Identifica una app y un momento. No necesitas pagar para hacer esa primera observación.</p><h3>Quiero separar mi teléfono de una actividad</h3><p>Primero prueba a dejarlo lejos si puedes hacerlo sin perder funciones importantes. Si quieres conservar herramientas del iPhone y pausar otras apps, prueba los límites del sistema. Foco es otra opción si valoras una barrera física y modos que puedes repetir.</p><h3>Quiero medir el resultado</h3><p>Mira el uso real en el sistema y la experiencia que querías proteger. En Foco, Mi tiempo registra las sesiones guardadas en ese iPhone. Una hora de sesión no demuestra que hayas evitado una hora de Instagram: no sabemos qué habrías hecho sin ella.</p><p>Si eliges Foco, revisa el <a href="/blog/cuanto-cuesta-foco/">costo total con envío</a>. Si los controles gratuitos resuelven tu necesidad, esa también es una buena decisión.</p>` },
        ],
        questions: [
            ['¿Tengo que desactivar Tiempo en pantalla para usar Foco?', 'Foco requiere autorización para gestionar las apps seleccionadas mediante las funciones del sistema. Sigue la configuración de la app y prueba cómo convive con los límites que ya tengas activos.'],
            ['¿Puedo mantener las apps que necesito?', 'Foco permite elegir qué bloquear o qué permitir. Apple también ofrece opciones de apps y contactos siempre permitidos. Comprueba las funciones esenciales antes de empezar una sesión.'],
        ],
    },
    {
        slug: 'foco-vs-brick-colombia', status: 'published', publishedAt: '2026-09-23', preparedAt: '2026-09-23', category: 'Comparaciones', number: '04',
        title: 'Foco vs. Brick: diferencias para comprar desde Colombia',
        description: 'Foco y Brick usan un objeto físico para pausar distracciones. Compara compatibilidad, formato y costos sin mezclar dólares con pesos ni inventar gastos de importación.',
        dek: 'Dos formas de poner una distancia entre tú y el scroll. La compra depende también de dónde y cómo las vas a usar.',
        cover: 'desk', sources: ['brickProduct', 'brickFAQ', 'brickTerms', 'focoSupport', 'focoPrice'], related: ['cuanto-cuesta-foco', 'foco-vs-tiempo-en-pantalla'],
        answer: 'Foco es una tarjeta con app para iPhone y compra en pesos colombianos. Brick es un dispositivo físico que anuncia compatibilidad con iPhone y Android. Ambos tienen un modelo de pago único actualmente. Compara el total entregado, la compatibilidad de tu equipo y el formato que usarías; no existe un ganador universal.',
        sections: [
            { id: 'comparacion', title: 'Lo esencial, sin una puntuación inventada', html: `<p><strong>Transparencia:</strong> este artículo lo publica Foco. Para Brick consultamos sus páginas oficiales; no afirmamos haber realizado una prueba de laboratorio ni una experiencia de uso independiente. Los datos externos se consultaron el 23 de septiembre de 2026 y pueden cambiar.</p><!-- visual:brick-table --><p>Brick anuncia un precio de US$59 para el dispositivo y compatibilidad con iOS 17 o posterior y Android 12 o posterior. Sus términos describen el modelo actual sin pagos recurrentes. <a href="#fuente-brickProduct">Producto</a>, <a href="#fuente-brickFAQ">compatibilidad</a> y <a href="#fuente-brickTerms">modelo de pago</a>.</p>` },
            { id: 'costo-en-colombia', title: 'Compara el total entregado, no solo la etiqueta', html: `<p>El precio de Foco para una tarjeta es <strong>{{focoUnit}} COP</strong>; con envío, el total es <strong>{{focoTotal}} COP</strong> antes de promociones. <a href="#fuente-focoPrice">Ver el precio vigente</a>.</p><p>Los US$59 anunciados por Brick no son una cotización entregada en Colombia. Antes de comprar, confirma que el destino esté disponible, el envío, los cargos aplicables y la conversión de tu medio de pago. No hemos validado una compra internacional a una dirección colombiana.</p><p>Para comparar presupuestos, anota el total final de cada checkout para el mismo destino y el mismo día. Si pagas en dólares, revisa también la tasa y las comisiones de tu medio de pago: el precio del dispositivo por sí solo no cuenta toda la compra.</p>` },
            { id: 'formato-y-compatibilidad', title: 'Piensa dónde va a vivir ese objeto', html: `<p>La tarjeta Foco cabe en la idea de un lugar de regreso: un escritorio, una repisa o el espacio donde decides empezar y cerrar el día. Si la dejas permanentemente al lado del teléfono, la distancia que buscabas se reduce. El formato es una decisión de rutina, no una garantía de eficacia.</p><p>Brick describe un dispositivo con imán y base antideslizante, sin batería. Puede tener sentido si prefieres dejar una pieza fija en un lugar visible. Esa es una diferencia de diseño, no una prueba de que funcione mejor para todas las personas. <a href="#fuente-brickProduct">Diseño anunciado por Brick</a>.</p><p>Si usas Android, Foco no es la opción compatible actualmente; Brick sí anuncia soporte. En iPhone, comprueba la versión del sistema y los permisos antes de comprar cualquiera. No des por hecho que cada función es idéntica entre plataformas.</p><!-- visual:modos -->` },
            { id: 'como-decidir', title: 'Tres preguntas antes de decidir', html: `<ol><li><strong>¿Qué quiero pausar?</strong> Haz una lista corta de apps y conserva las funciones esenciales. Si todavía no tienes claro el problema, empieza con los controles gratuitos del teléfono.</li><li><strong>¿Dónde dejaré el objeto?</strong> Elige un sitio al que volver sea una decisión consciente, sin poner en riesgo una necesidad importante.</li><li><strong>¿Cuál es el costo final y cómo consigo ayuda?</strong> Revisa entrega, devolución, soporte y las reglas para una tarjeta o dispositivo perdido.</li></ol><p>Para Foco, la app contempla sesiones con duración o Hasta volver y tres desbloqueos de emergencia por cuenta. Lee cómo funcionan antes de depender de ellos. <a href="#fuente-focoSupport">Ayuda de Foco</a>.</p><p>Si tu prioridad es no comprar hardware, nuestra comparación de <a href="/blog/foco-vs-tiempo-en-pantalla/">Foco con Tiempo en pantalla</a> puede ser más útil. Si buscas el presupuesto de Foco, aquí está el <a href="/blog/cuanto-cuesta-foco/">desglose de tarjeta y envío</a>.</p>` },
        ],
        questions: [
            ['¿Brick necesita una suscripción?', 'Sus términos oficiales consultados describen un pago único por el hardware y acceso a la app sin cargos recurrentes bajo el modelo actual. Revisa esos términos antes de comprar.'],
            ['¿Foco es más barato que Brick en Colombia?', 'No afirmamos un ahorro final sin una cotización de Brick entregada al mismo destino. Foco muestra el cobro en COP; Brick anuncia el dispositivo en USD y pueden aplicar otros cargos.'],
        ],
    },
    {
        slug: 'cuanto-cuesta-foco', status: 'published', publishedAt: '2026-09-23', preparedAt: '2026-09-23', category: 'Antes de comprar', number: '05',
        title: 'Cuánto cuesta Foco en Colombia: tarjeta, envío y pago único',
        description: 'Consulta el precio de Foco en pesos colombianos, qué incluye, cuánto cuesta el envío y cómo comparar una compra única con una suscripción o una alternativa gratuita.',
        dek: 'El precio completo. Sin convertir tu atención en una promesa de retorno.',
        cover: 'desk', sources: ['focoPrice', 'focoSupport', 'focoTerms'], related: ['foco-vs-tiempo-en-pantalla', 'foco-vs-brick-colombia', 'como-usar-menos-el-celular'],
        answer: 'Una tarjeta Foco cuesta {{focoUnit}} COP. Para la opción de una tarjeta, el envío es {{focoShipping}} COP: total {{focoTotal}} COP antes de promociones. Es un pago único, sin suscripción para usar Foco. El importe definitivo, la disponibilidad y los descuentos aplicables se confirman en el checkout.',
        sections: [
            { id: 'precio-y-envio', title: 'Cuánto pagas por cada opción', html: `<p>Comprar una tarjeta y comprar varias no tienen el mismo total ni el mismo envío. Aquí puedes ver el desglose de cada opción, en pesos colombianos y antes de cupones adicionales.</p><!-- visual:price-table --><p>Una promoción puede cambiar el importe que pagas. Si tienes un código, aplícalo y verifica el resumen antes de continuar al pago. La referencia final es el <a href="#fuente-focoPrice">checkout</a>, no una captura que alguien te haya compartido.</p>` },
            { id: 'precio-por-tarjeta', title: 'Qué cambia cuando compras varias', html: `<!-- visual:price-chart --><p>El gráfico divide el total de cada paquete, incluido su envío, entre el número de tarjetas. No significa que puedas comprar una tarjeta suelta al valor unitario de un paquete. Tampoco implica que necesites varias para comenzar: compra la cantidad que realmente vas a usar.</p><p>Una misma tarjeta puede usarse en varios iPhone con cuentas propias; cada iPhone mantiene una tarjeta vinculada a la vez. Revisa si compartir una encaja con los horarios y lugares de las personas que la usarán. <a href="#fuente-focoSupport">Compatibilidad y uso compartido</a>.</p>` },
            { id: 'que-incluye', title: 'Qué incluye, y qué no estás comprando', html: `<p>Foco combina una tarjeta física con una app para iPhone. La tarjeta se reutiliza en las sesiones; no hay una mensualidad para el funcionamiento descrito del producto. Necesitas un iPhone compatible con iOS 17.6 o posterior y completar la configuración indicada por la app.</p><p>La herramienta permite elegir apps y sitios, crear modos y programar rutinas. No incluye un teléfono, no funciona en Android y no equivale a atención psicológica. Comprar Foco no garantiza reducir una cantidad determinada de horas.</p><p>También conviene distinguir dos cifras: las sesiones que ves en Mi tiempo y el uso de apps que registra el iPhone. No prometemos convertir automáticamente el precio en “horas ganadas” ni en un rendimiento económico.</p>` },
            { id: 'gratis-unico-suscripcion', title: 'Gratis, pago único o suscripción: cómo comparar', html: `<p><strong>Una opción gratuita</strong> tiene sentido si resuelve tu necesidad con lo que ya tienes. Prueba los controles del teléfono antes de asumir que necesitas otra herramienta. Nuestra guía de <a href="/blog/foco-vs-tiempo-en-pantalla/">Tiempo en pantalla y Foco</a> explica la diferencia.</p><p><strong>Un pago único</strong> concentra el costo al principio. Incluye el envío en tu presupuesto y verifica qué servicio acompaña al dispositivo, qué pasa si lo pierdes y qué condiciones se aplican.</p><p><strong>Una suscripción</strong> requiere comparar el importe del periodo que usarás, no solo un “desde” mensual. Revisa la moneda, el cobro anual o mensual, la renovación, la cancelación y si un accesorio se compra aparte.</p><p>Compara el mismo plazo, las funciones que necesitas y el costo total. Si solo usarás una herramienta durante un mes, tu decisión puede ser distinta de la de alguien que quiere incorporarla a una rutina permanente. Pagar más no garantiza que encaje mejor contigo.</p>` },
            { id: 'antes-de-pagar', title: 'Antes de pagar', html: `<ul><li>Confirma que tu iPhone sea compatible y que puedas conceder los permisos necesarios.</li><li>Revisa la cantidad, el envío y cualquier descuento en el resumen de compra.</li><li>Lee las condiciones de entrega y devolución. Un plazo de entrega no empieza antes de que el pago sea aprobado.</li><li>Consulta cómo cerrar una sesión y qué ocurre si pierdes la tarjeta.</li></ul><p>Foco informa un plazo de entrega en Colombia de 3 a 10 días hábiles desde el pago aprobado, incluido el despacho. Consulta siempre las <a href="#fuente-focoTerms">condiciones vigentes</a>, especialmente si necesitas recibirla para una fecha concreta.</p><p>Si todavía estás decidiendo qué cambiar de tu uso del teléfono, empieza por el <a href="/blog/como-usar-menos-el-celular/">plan de una semana</a>. La compra debería responder a una necesidad que ya identificaste.</p>` },
        ],
        questions: [
            ['¿La app tiene una mensualidad?', 'No hay una suscripción para usar Foco según el funcionamiento y las condiciones actuales del producto. La tarjeta se paga una vez.'],
            ['¿El envío está incluido?', 'Depende de la cantidad elegida. La tabla muestra el envío de cada opción y el total antes de cupones; confirma el resumen final del checkout.'],
        ],
    },
];
